name: 'Generate Checksum'
description: Generates a checksum file from a list of glob patterns
inputs:
  method:
    description: Hashing algorithm to use [md5, sha1, sha256, sha512]
    required: false
    default: sha256
  output:
    description: Output file path
    required: false
    default: checksum.txt
  patterns:
    description: List of glob patterns to use for matching files
    required: true
runs:
  using: docker
  image: docker://ghcr.io/jmgilman/actions-generate-checksum:latest
  args:
    - ${{ inputs.method }}
    - ${{ inputs.output }}
    - ${{ inputs.patterns }}